Repository Open-Orange-Button/Orange-Button-Taxonomy, pull requests merged in 2022-09, with the labels that each got.

#90 create 2207.1.0 whatsnew
  docs/whatsnew/2207.1.0.rst
Labels: documentation

#91 Adds AHJLevelCode and elements for special cases.
  Master-OB-OpenAPI.json
  docs/whatsnew/2207.1.0.rst
Labels: minor

#84 Adds Scope to Task, Comment, BOS, BOM and adds JobID to Job/ Updates …
  Master-OB-OpenAPI.json
  docs/whatsnew/2207.1.0.rst
Labels: minor

#88 Overhaul EnergyModel
  Master-OB-OpenAPI.json
  docs/whatsnew/2207.1.0.rst
Labels: major

#105 make ForecastScope again, remove ForecastScopeID
  Master-OB-OpenAPI.json
  docs/whatsnew/2207.1.0.rst
Labels: enhancement, major
