Repository Open-Orange-Button/Orange-Button-Taxonomy, pull requests merged in 2023-04, with the labels that each got.

#219 Adds changes from issues 217,218
  Master-OB-OpenAPI.json
  docs/whatsnew/2209.1.0.rst
Labels: minor

#209 Make trio: EnergyUsage, EnergyConsumption, EnergyProduction
  Master-OB-OpenAPI.json
  docs/whatsnew/2209.1.0.rst
Labels: enhancement, major

#221 Creates JobStatus element.
  Master-OB-OpenAPI.json
  docs/whatsnew/2209.1.0.rst
Labels: enhancement, minor
